/* Halabja Group — Translation dictionary
   Languages: en (English LTR), ku (Kurdish Sorani RTL), ar (Arabic RTL)
   Usage: elements with data-i18n="key" are updated on language change.
          elements with data-i18n-html="key" accept innerHTML (for bold/spans).
          elements with data-i18n-placeholder="key" update placeholder attr.
*/

const TRANSLATIONS = {
  en: {
    /* NAV */
    nav_about:      'About',
    nav_companies:  'Companies',
    nav_news:       'News',
    nav_branches:   'Branches',
    nav_careers:    'Careers',
    nav_tagline:    'Trust the Expertise',
    /* HERO */
    hero_headline:  'Trust the',
    hero_accent:    'Expertise',
    hero_sub:       'A diversified group operating across construction, petroleum, and trading — delivering infrastructure, energy, and commerce that powers the region.',
    hero_btn1:      'Explore Services',
    hero_btn2:      'View Projects',
    /* STATS */
    stat1_n: '35+',  stat1_l: 'Years of Experience',
    stat2_n: '150+', stat2_l: 'Projects Completed',
    stat3_n: '8',    stat3_l: 'Core Sectors',
    stat4_n: '500+', stat4_l: 'Skilled Employees',
    /* SECTORS */
    sectors_eyebrow: 'What We Do',
    sectors_h1: 'Eight Sectors.',
    sectors_h2: 'One Group.',
    sector_service:     'Service',
    sector_investment:  'Investment',
    sector_energy:      'Energy',
    sector_education:   'Education',
    sector_trading:     'Trading',
    sector_realestate:  'Real Estate',
    sector_construction:'Construction & Industrial',
    sector_food:        'Food Industry',
    /* ABOUT SECTION (homepage) */
    about_eyebrow: 'Who We Are',
    about_h1: 'A Legacy of',
    about_h2: 'Trust & Growth',
    about_body: 'Founded in Halabja in 1992, Halabja Group has grown from a single trading company into one of Kurdistan\'s most diversified conglomerates. With 23 subsidiaries spanning eight sectors, we are committed to the reconstruction and sustainable development of Iraq.',
    about_val1_title: 'Integrity',
    about_val1_body:  'Transparent dealings and commitment to every promise.',
    about_val2_title: 'Excellence',
    about_val2_body:  'Consistently elevating quality across all sectors.',
    about_val3_title: 'Sustainability',
    about_val3_body:  'Building for the long-term — our clients, our community.',
    about_val4_title: 'Community',
    about_val4_body:  'Supporting local talent and generating job opportunities.',
    about_link: 'Our Full Story →',
    /* NEWS */
    news_eyebrow: 'Latest Updates',
    news_h1: 'News &',
    news_h2: 'Announcements',
    news_viewall: 'View All →',
    /* BRANCHES */
    branches_eyebrow: 'Our Presence',
    branches_h1: 'Where We',
    branches_h2: 'Operate',
    branches_desc: 'Halabja Group maintains strategic offices across four countries, enabling global sourcing, partnerships, and regional delivery.',
    branch_iraq:   'Iraq',
    branch_uae:    'UAE',
    branch_china:  'China',
    branch_turkey: 'Turkey',
    branch_iraq_sub:   'Sulaymaniyah — Headquarters',
    branch_uae_sub:    'Dubai — Trading Office',
    branch_china_sub:  'Yiwu — Sourcing Office',
    branch_turkey_sub: 'Istanbul — Regional Office',
    /* FOOTER */
    footer_nav:     'Navigate',
    footer_sectors: 'Sectors',
    footer_brands:  'Subsidiary Brands',
    footer_copy:    '© 2026 Halabja Group. All rights reserved.',
    footer_tagline: 'Trust the Expertise',
    footer_desc:    'A diversified enterprise spanning eight sectors and four countries — committed to the reconstruction and development of Kurdistan and Iraq.',
    /* ABOUT PAGE */
    ap_eyebrow:    'Halabja Group · Est. 1992',
    ap_h1a:        'Built on',
    ap_h1b:        'Trust.',
    ap_h1c:        'Driven by',
    ap_h1d:        'Expertise.',
    ap_scroll:     'Scroll to Explore',
    ap_stats_eyebrow: 'By the Numbers',
    ap_stats_h1:   'Our Impact',
    ap_stats_h2:   'at a Glance',
    ap_stat1_n: '35+', ap_stat1_l: 'Years Active',
    ap_stat2_n: '8',   ap_stat2_l: 'Sectors',
    ap_stat3_n: '500+',ap_stat3_l: 'Employees',
    ap_stat4_n: '23',  ap_stat4_l: 'Subsidiaries',
    ap_msg_eyebrow:  'Leadership',
    ap_msg_h1:       'Chairman\'s',
    ap_msg_h2:       'Message',
    ap_msg_name:     'Aso Bamoki',
    ap_msg_title:    'Chairman, Halabja Group',
    ap_msg_body1:    'Since our founding in Halabja in 1992, we have been driven by a singular mission: to contribute to the prosperity and development of our people and our homeland.',
    ap_msg_body2:    'Our overarching vision is to contribute to a better country, thriving on sustainable progress and lasting prosperity — for both current and future generations.',
    ap_msg_quote:    '"Our goal is to be a trusted provider of services and businesses that support the country\'s economic growth and development. By providing cutting-edge technology, creating job opportunities, and supporting local talent, we intend to leverage our expertise, resources, and strengths to improve the lives of citizens."',
    ap_msg_attr:     '— Aso Bamoki, Chairman · Halabja Group',
    ap_timeline_eyebrow: 'Our Journey',
    ap_timeline_h1:  'Milestones &',
    ap_timeline_h2:  'Subsidiaries',
    ap_timeline_drag:'12 Companies · Drag to Explore →',
    ap_values_eyebrow: 'Our Foundation',
    ap_values_h1:    'What We',
    ap_values_h2:    'Stand For',
    ap_values_desc:  'Our values are not words on a wall — they are the principles that guide every decision, every project, and every relationship we build across our eight sectors.',
    ap_val1_n:'01', ap_val1_t:'Integrity',    ap_val1_b:'Transparent dealings and unwavering commitment to every promise made to our clients and partners.',
    ap_val2_n:'02', ap_val2_t:'Excellence',   ap_val2_b:'Consistently elevating the quality of our products and services to meet the highest standards.',
    ap_val3_n:'03', ap_val3_t:'Sustainability',ap_val3_b:'Building for the long term — for our clients, our communities, and our environment.',
    ap_val4_n:'04', ap_val4_t:'Community',    ap_val4_b:'Supporting local talent and generating ample job opportunities for our fellow citizens.',
    ap_cta_h1:   'Join the',
    ap_cta_h2:   'Halabja Group',
    ap_cta_h3:   'team',
    ap_cta_sub:  'We are always looking for talented, driven individuals to grow with us.',
    ap_cta_btn:  'View Open Positions →',
    /* COMPANIES PAGE */
    cp_eyebrow: 'Our Portfolio',
    cp_h1: '23 Companies.',
    cp_h2: '8 Sectors.',
    cp_sub: 'From construction and energy to education and food, Halabja Group\'s subsidiaries span the full breadth of Iraq\'s growing economy.',
    cp_filter_all:         'All',
    cp_filter_construction:'Construction',
    cp_filter_energy:      'Energy',
    cp_filter_trading:     'Trading',
    cp_filter_realestate:  'Real Estate',
    cp_filter_education:   'Education',
    cp_filter_food:        'Food Industry',
    cp_filter_investment:  'Investment',
    cp_filter_services:    'Services',
    cp_learnmore: 'Learn More',
    /* NEWS PAGE */
    np_eyebrow: 'Latest Updates',
    np_h1: 'News &',
    np_h2: 'Announcements',
    np_sub: 'Stay up to date with the latest projects, milestones, and developments from Halabja Group and its subsidiaries.',
    np_filter_all:           'All',
    np_filter_event:         'Events',
    np_filter_project:       'Projects',
    np_filter_corporate:     'Corporate',
    np_filter_people:        'People',
    np_filter_infrastructure:'Infrastructure',
    np_read_full: 'Read full story',
    np_read_more: 'Read more',
    np_all_stories: 'All Stories',
    /* CAREERS PAGE */
    crp_eyebrow: 'Join Our Team',
    crp_h1: 'Build Your',
    crp_h2: 'Career With Us',
    crp_sub: 'We are looking for talented, driven individuals to help us grow across eight sectors and four countries.',
    crp_stat1_n:'500+', crp_stat1_l:'Employees',
    crp_stat2_n:'23',   crp_stat2_l:'Companies',
    crp_stat3_n:'8',    crp_stat3_l:'Sectors',
    crp_stat4_n:'4',    crp_stat4_l:'Countries',
    crp_filter_all:        'All',
    crp_filter_construction:'Construction',
    crp_filter_energy:     'Energy',
    crp_filter_trading:    'Trading',
    crp_filter_education:  'Education',
    crp_filter_realestate: 'Real Estate',
    crp_filter_admin:      'Admin',
    crp_apply_btn: 'Apply Now',
    crp_open_h1: 'Don\'t see the right role?',
    crp_open_h2: 'Send an Open Application',
    crp_open_sub: 'We\'re always looking for talented people. Tell us about yourself and we\'ll reach out when the right opportunity arises.',
    crp_open_btn: 'Send Open Application →',
    /* MODAL */
    modal_title:   'Apply for this Position',
    modal_close:   '×',
    modal_sec1:    'Personal Information',
    modal_name:    'Full Name',
    modal_email:   'Email Address',
    modal_phone:   'Phone Number',
    modal_nationality: 'Nationality',
    modal_sec2:    'Professional Background',
    modal_exp:     'Years of Experience',
    modal_jobtitle:'Current Job Title',
    modal_linkedin:'LinkedIn Profile (optional)',
    modal_skills:  'Key Skills',
    modal_skills_ph:'Type skill and press Enter…',
    modal_cover:   'Cover Letter',
    modal_cover_ph:'Tell us why you\'re a great fit…',
    modal_cv:      'Upload CV',
    modal_cv_sub:  'Drag & drop or click to upload — PDF, DOC, DOCX',
    modal_submit:  'Submit Application',
    modal_success_h: 'Application Received!',
    modal_success_b: 'Thank you for applying. Our team will review your application and be in touch within 5–7 business days.',
    modal_back:    '← Back to Positions',
    /* COMMON */
    back_main: '← Back to main site',
    copyright:  '© 2026 Halabja Group. All rights reserved.',
  },

  /* ═══════════════════════════════════════════════════════════════
     KURDISH SORANI  (کوردی سۆرانی)  — RTL
  ═══════════════════════════════════════════════════════════════ */
  ku: {
    nav_about:      'دەربارە',
    nav_companies:  'کۆمپانیاکان',
    nav_news:       'هەواڵ',
    nav_branches:   'لقەکان',
    nav_careers:    'دەرفەتی کار',
    nav_tagline:    'پشتبەستن بە شارەزایی',
    hero_headline:  'پشتبەستن بە',
    hero_accent:    'شارەزایی',
    hero_sub:       'گروپێکی جۆراوجۆر کە لە بواری بیناسازی، نەوت، و بازرگانیدا کار دەکات — پێشکەشکردنی بنەرەت، وزە، و بازرگانییەکی کە هەرێمەکە بەرز دەکاتەوە.',
    hero_btn1:      'خزمەتگوزارییەکان',
    hero_btn2:      'پرۆژەکان',
    stat1_n: '٣٥+',  stat1_l: 'ساڵی ئەزموون',
    stat2_n: '١٥٠+', stat2_l: 'پرۆژەی تەواوبوو',
    stat3_n: '٨',    stat3_l: 'بەشی سەرەکی',
    stat4_n: '٥٠٠+', stat4_l: 'کارمەندی پسپۆڕ',
    sectors_eyebrow: 'چی دەکەین',
    sectors_h1: 'هەشت بەش.',
    sectors_h2: 'یەک گروپ.',
    sector_service:     'خزمەتگوزاری',
    sector_investment:  'وەبەرهێنان',
    sector_energy:      'وزە',
    sector_education:   'پەروەردە',
    sector_trading:     'بازرگانی',
    sector_realestate:  'خانووبەرە',
    sector_construction:'بیناسازی و پیشەسازی',
    sector_food:        'پیشەسازی خواردنی',
    about_eyebrow: 'کێین',
    about_h1: 'مێژووێکی',
    about_h2: 'پشتبەستن و گەشە',
    about_body: 'لە ساڵی ١٩٩٢ لە هەڵەبجە دامەزرابوو، گروپی هەڵەبجە لە کۆمپانیایەکی بازرگانی تەنها گەشەی کردووە بۆ یەکێک لە کۆنگلۆمێراتە جۆراوجۆرەکانی کوردستان. لەگەڵ ٢٣ کۆمپانیای خاوەندار لە هەشت بەشدا، ئێمە پابەندی دامەزرانەوە و گەشەی بەردەوامی عێراقین.',
    about_val1_title: 'راستبازی',
    about_val1_body:  'مامەڵەی ئاشکرا و پابەندبوون بە هەموو پەیمان.',
    about_val2_title: 'تایبەتمەندی',
    about_val2_body:  'بەردەوام بالابردنی کوالێتی لە هەموو بەشەکاندا.',
    about_val3_title: 'بەردەوامی',
    about_val3_body:  'بینا نانی بۆ ئێستا و داهاتوو — کریاران، کۆمەڵگا، ژینگە.',
    about_val4_title: 'کۆمەڵگا',
    about_val4_body:  'پشتگیری پسپۆڕانی هەرێمی و دروستکردنی دەرفەتی کار.',
    about_link: 'چیرۆکی تەواوی ئێمە →',
    news_eyebrow: 'دوایین نوێکارییەکان',
    news_h1: 'هەواڵ و',
    news_h2: 'ڕاگەیاندنەکان',
    news_viewall: 'هەموو بینە →',
    branches_eyebrow: 'ئەمکانی مان',
    branches_h1: 'شوێنی',
    branches_h2: 'کارمان',
    branches_desc: 'گروپی هەڵەبجە ئۆفیسی ستراتیژیی لە چوار وڵاتدا هەیە، کە چاوپێکەوتنی جیهانی، هاوبەشەکان، و گەیاندنی هەرێمی دروست دەکات.',
    branch_iraq:   'عێراق',
    branch_uae:    'ئیمارات',
    branch_china:  'چین',
    branch_turkey: 'تورکیا',
    branch_iraq_sub:   'سلێمانی — نووسینگەی سەرەکی',
    branch_uae_sub:    'دوبەی — ئۆفیسی بازرگانی',
    branch_china_sub:  'یێووو — ئۆفیسی سەرچاوەکان',
    branch_turkey_sub: 'ئەستەمبوڵ — ئۆفیسی هەرێمی',
    footer_nav:     'پێوەندی',
    footer_sectors: 'بەشەکان',
    footer_brands:  'براندەکانی کۆمپانیا',
    footer_copy:    '© ٢٠٢٦ گروپی هەڵەبجە. هەموو مافەکان پارێزراون.',
    footer_tagline: 'پشتبەستن بە شارەزایی',
    footer_desc:    'کارگێڕییەکی جۆراوجۆر کە لە هەشت بەش و چوار وڵاتدا گستراوە — پابەندی دامەزرانەوە و گەشەی بەردەوامی کوردستان و عێراق.',
    ap_eyebrow:    'گروپی هەڵەبجە · دامەزراوی ١٩٩٢',
    ap_h1a:        'بیناکراوە لەسەر',
    ap_h1b:        'پشتبەستن.',
    ap_h1c:        'بەهێزکراوە بە',
    ap_h1d:        'شارەزایی.',
    ap_scroll:     'بگەڕێ خوارەوە',
    ap_stats_eyebrow: 'بە ژمارە',
    ap_stats_h1:   'کاریگەریمان',
    ap_stats_h2:   'بە کورتی',
    ap_stat1_n: '٣٥+', ap_stat1_l: 'ساڵ چالاک',
    ap_stat2_n: '٨',   ap_stat2_l: 'بەش',
    ap_stat3_n: '٥٠٠+',ap_stat3_l: 'کارمەند',
    ap_stat4_n: '٢٣',  ap_stat4_l: 'کۆمپانیا',
    ap_msg_eyebrow: 'سەرکردایەتی',
    ap_msg_h1:      'پەیامی',
    ap_msg_h2:      'سەرۆک',
    ap_msg_name:    'ئاسو بامۆکی',
    ap_msg_title:   'سەرۆک، گروپی هەڵەبجە',
    ap_msg_body1:   'لە دامەزراندنمانەوە لە هەڵەبجە لە ساڵی ١٩٩٢، مەبەستێکی تەنها مان بە ئامانج بووە: بەشداری کردن لە خۆشی و گەشەی خەڵکی و وڵاتی خۆمان.',
    ap_msg_body2:   'بینینی گشتیمان ئەوەیە کە بەشداری وڵاتێکی باشتر بکەین کە لەسەر پێشکەوتنی بەردەوام و خۆشبەختی مامناوەند بنیاد نراوە.',
    ap_msg_quote:   '"ئامانجی ئێمە ئەوەیە کە بین دابینکەری خزمەتگوزاری و کارو بازرگانی پشتیوانیکراو کە گەشەی ئابووری و گەشەپێدانی وڵات پشتیوانی دەکات."',
    ap_msg_attr:    '— ئاسو بامۆکی، سەرۆک · گروپی هەڵەبجە',
    ap_timeline_eyebrow: 'گەشتەکەمان',
    ap_timeline_h1: 'چاوپێکەوتنەکان و',
    ap_timeline_h2: 'کۆمپانیاکان',
    ap_timeline_drag:'١٢ کۆمپانیا · بکێش بۆ گەڕان →',
    ap_values_eyebrow: 'بنچینەکەمان',
    ap_values_h1:   'بۆچی',
    ap_values_h2:   'ئێستاواین',
    ap_values_desc:  'بەهاکانمان وشە لەسەر دیوار نین — ئەوانە ئەو بنچینانەن کە هەر بڕیار، هەر پرۆژە، و هەر پەیوەندییەک ئەندازەی دەکات.',
    ap_val1_n:'٠١', ap_val1_t:'راستبازی',    ap_val1_b:'مامەڵەی ئاشکرا و پابەندبوونی بەردەوام بە هەموو پەیمان لەگەڵ کریاران و هاوبەشەکان.',
    ap_val2_n:'٠٢', ap_val2_t:'تایبەتمەندی', ap_val2_b:'بەردەوام بالابردنی کوالێتی بەرهەم و خزمەتگوزارییەکانمان بۆ گەیشتن بە بەرزترین ئاستەکان.',
    ap_val3_n:'٠٣', ap_val3_t:'بەردەوامی',   ap_val3_b:'بیناکردن بۆ درێژخایەن — کریاران، کۆمەڵگاکانمان، و ژینگەمان.',
    ap_val4_n:'٠٤', ap_val4_t:'کۆمەڵگا',    ap_val4_b:'پشتگیری پسپۆڕانی هەرێمی و دروستکردنی دەرفەتی کاری زۆر بۆ هاووڵاتیانمان.',
    ap_cta_h1:  'یەکبە',
    ap_cta_h2:  'گروپی هەڵەبجە',
    ap_cta_h3:  '',
    ap_cta_sub: 'بەردەوام بەدوای کەسانی بەتوانا و پێگەیشتووی دەگەڕێین بۆ گەشەکردن لەگەڵمان.',
    ap_cta_btn: 'شوێنە کراوەکان ببینە →',
    cp_eyebrow: 'پۆرتفۆلیۆمان',
    cp_h1: '٢٣ کۆمپانیا.',
    cp_h2: '٨ بەش.',
    cp_sub: 'لە بیناسازی و وزە تا پەروەردە و خواردن، کۆمپانیاکانی گروپی هەڵەبجە هەموو ئابووری گەشەکەی عێراق دادەگرن.',
    cp_filter_all:         'هەموو',
    cp_filter_construction:'بیناسازی',
    cp_filter_energy:      'وزە',
    cp_filter_trading:     'بازرگانی',
    cp_filter_realestate:  'خانووبەرە',
    cp_filter_education:   'پەروەردە',
    cp_filter_food:        'خواردن',
    cp_filter_investment:  'وەبەرهێنان',
    cp_filter_services:    'خزمەتگوزاری',
    cp_learnmore: 'زیاتر بزانە',
    np_eyebrow: 'دوایین نوێکارییەکان',
    np_h1: 'هەواڵ و',
    np_h2: 'ڕاگەیاندنەکان',
    np_sub: 'لە دوایین پرۆژەکان، گەیشتنەکان، و گەشەپێدانەکانی گروپی هەڵەبجە و کۆمپانیاکانیەوە ئاگادار بە.',
    np_filter_all:           'هەموو',
    np_filter_event:         'ڕووداوەکان',
    np_filter_project:       'پرۆژەکان',
    np_filter_corporate:     'کۆرپۆرەیت',
    np_filter_people:        'کەسەکان',
    np_filter_infrastructure:'بنەرەت',
    np_read_full: 'چیرۆکی تەواو بخوێنەوە',
    np_read_more: 'زیاتر بخوێنەوە',
    np_all_stories: 'هەموو چیرۆکەکان',
    crp_eyebrow: 'بەشداربە لە تیمەکەمان',
    crp_h1: 'کارەکەت',
    crp_h2: 'لەگەڵمان بنیاد بنێ',
    crp_sub: 'بەدوای کەسانی بەتوانا و پێگەیشتووی دەگەڕێین بۆ یارمەتیمان لە گەشەکردن لە هەشت بەش و چوار وڵاتدا.',
    crp_stat1_n:'٥٠٠+', crp_stat1_l:'کارمەند',
    crp_stat2_n:'٢٣',   crp_stat2_l:'کۆمپانیا',
    crp_stat3_n:'٨',    crp_stat3_l:'بەش',
    crp_stat4_n:'٤',    crp_stat4_l:'وڵات',
    crp_filter_all:        'هەموو',
    crp_filter_construction:'بیناسازی',
    crp_filter_energy:     'وزە',
    crp_filter_trading:    'بازرگانی',
    crp_filter_education:  'پەروەردە',
    crp_filter_realestate: 'خانووبەرە',
    crp_filter_admin:      'کارگێڕی',
    crp_apply_btn: 'داوا بکە',
    crp_open_h1: 'شوێنی گونجاوت نەدیتی؟',
    crp_open_h2: 'داواکاری کراوە بنێرە',
    crp_open_sub: 'بەردەوام بەدوای کەسانی بەتوانا دەگەڕێین. خۆت بنوێنە و کاتێک دەرفەتی گونجاو هەبوو پەیوەندیت پێوە دەکەین.',
    crp_open_btn: 'داواکاری کراوە بنێرە →',
    modal_title:   'داواکاری ئەم شوێنە بکە',
    modal_close:   '×',
    modal_sec1:    'زانیاری کەسی',
    modal_name:    'ناوی تەواو',
    modal_email:   'ئیمەیڵ',
    modal_phone:   'ژمارەی مۆبایل',
    modal_nationality: 'نەتەوایەتی',
    modal_sec2:    'پیشەیی',
    modal_exp:     'ساڵانی ئەزموون',
    modal_jobtitle:'ناونیشانی کاری ئێستا',
    modal_linkedin:'لینکدین (ئارەزوومەندانە)',
    modal_skills:  'بەهرەکانی سەرەکی',
    modal_skills_ph:'بەهرە بنووسە و Enter بدە…',
    modal_cover:   'نامەی پووشپەڕ',
    modal_cover_ph:'بگوێرە بۆچی گونجاوی...',
    modal_cv:      'CV بکێشە',
    modal_cv_sub:  'بکێشە و بخەرە یان کلیک بکە — PDF, DOC, DOCX',
    modal_submit:  'داواکاری بنێرە',
    modal_success_h: 'داواکاریەکەت وەرگیراو!',
    modal_success_b: 'سوپاس بۆ داواکارییەکەت. تیمەکەمان داواکارییەکەت پشکنین دەکات و لەنێوان ٥-٧ ڕۆژی کاریدا پەیوەندیت پێوە دەکەین.',
    modal_back:    '← گەڕانەوە بۆ شوێنەکان',
    back_main: '← گەڕانەوە بۆ مالپەڕی سەرەکی',
    copyright:  '© ٢٠٢٦ گروپی هەڵەبجە. هەموو مافەکان پارێزراون.',
  },

  /* ═══════════════════════════════════════════════════════════════
     ARABIC  (العربية)  — RTL
  ═══════════════════════════════════════════════════════════════ */
  ar: {
    nav_about:      'عن الشركة',
    nav_companies:  'الشركات',
    nav_news:       'الأخبار',
    nav_branches:   'الفروع',
    nav_careers:    'وظائف',
    nav_tagline:    'ثق بالخبرة',
    hero_headline:  'ثق',
    hero_accent:    'بالخبرة',
    hero_sub:       'مجموعة متنوعة تعمل في قطاعات البناء والنفط والتجارة — تقدم البنية التحتية والطاقة والتجارة التي تغذي المنطقة.',
    hero_btn1:      'استكشف خدماتنا',
    hero_btn2:      'عرض المشاريع',
    stat1_n: '٣٥+',  stat1_l: 'سنوات خبرة',
    stat2_n: '١٥٠+', stat2_l: 'مشاريع مكتملة',
    stat3_n: '٨',    stat3_l: 'قطاعات أساسية',
    stat4_n: '٥٠٠+', stat4_l: 'موظف متخصص',
    sectors_eyebrow: 'ما نقوم به',
    sectors_h1: 'ثمانية قطاعات.',
    sectors_h2: 'مجموعة واحدة.',
    sector_service:     'الخدمات',
    sector_investment:  'الاستثمار',
    sector_energy:      'الطاقة',
    sector_education:   'التعليم',
    sector_trading:     'التجارة',
    sector_realestate:  'العقارات',
    sector_construction:'البناء والصناعة',
    sector_food:        'الصناعة الغذائية',
    about_eyebrow: 'من نحن',
    about_h1: 'إرث من',
    about_h2: 'الثقة والنمو',
    about_body: 'تأسست في حلبجة عام ١٩٩٢، نمت مجموعة حلبجة من شركة تجارية واحدة لتصبح أحد أكثر التكتلات تنوعاً في كردستان. بـ٢٣ شركة تابعة في ثمانية قطاعات، نلتزم بإعادة الإعمار والتنمية المستدامة للعراق.',
    about_val1_title: 'النزاهة',
    about_val1_body:  'تعاملات شفافة والتزام بكل وعد.',
    about_val2_title: 'التميز',
    about_val2_body:  'رفع مستوى الجودة باستمرار في جميع القطاعات.',
    about_val3_title: 'الاستدامة',
    about_val3_body:  'البناء على المدى البعيد — عملاؤنا، مجتمعنا، بيئتنا.',
    about_val4_title: 'المجتمع',
    about_val4_body:  'دعم الكفاءات المحلية وخلق فرص العمل.',
    about_link: 'قصتنا الكاملة →',
    news_eyebrow: 'آخر التحديثات',
    news_h1: 'الأخبار و',
    news_h2: 'الإعلانات',
    news_viewall: 'عرض الكل →',
    branches_eyebrow: 'تواجدنا',
    branches_h1: 'مناطق',
    branches_h2: 'عملنا',
    branches_desc: 'تحتفظ مجموعة حلبجة بمكاتب استراتيجية في أربع دول، مما يتيح الحصول على موارد عالمية وشراكات وتسليم إقليمي.',
    branch_iraq:   'العراق',
    branch_uae:    'الإمارات',
    branch_china:  'الصين',
    branch_turkey: 'تركيا',
    branch_iraq_sub:   'السليمانية — المقر الرئيسي',
    branch_uae_sub:    'دبي — مكتب التجارة',
    branch_china_sub:  'يوو — مكتب المصادر',
    branch_turkey_sub: 'إسطنبول — المكتب الإقليمي',
    footer_nav:     'التنقل',
    footer_sectors: 'القطاعات',
    footer_brands:  'العلامات التجارية',
    footer_copy:    '© ٢٠٢٦ مجموعة حلبجة. جميع الحقوق محفوظة.',
    footer_tagline: 'ثق بالخبرة',
    footer_desc:    'مؤسسة متنوعة تمتد عبر ثمانية قطاعات وأربع دول — ملتزمة بإعادة إعمار وتطوير كردستان والعراق.',
    ap_eyebrow:    'مجموعة حلبجة · التأسيس ١٩٩٢',
    ap_h1a:        'مبنية على',
    ap_h1b:        'الثقة.',
    ap_h1c:        'مدفوعة بـ',
    ap_h1d:        'الخبرة.',
    ap_scroll:     'مرر للاستكشاف',
    ap_stats_eyebrow: 'بالأرقام',
    ap_stats_h1:   'تأثيرنا',
    ap_stats_h2:   'في لمحة',
    ap_stat1_n: '٣٥+', ap_stat1_l: 'سنة نشاط',
    ap_stat2_n: '٨',   ap_stat2_l: 'قطاعات',
    ap_stat3_n: '٥٠٠+',ap_stat3_l: 'موظف',
    ap_stat4_n: '٢٣',  ap_stat4_l: 'شركة',
    ap_msg_eyebrow: 'القيادة',
    ap_msg_h1:      'رسالة',
    ap_msg_h2:      'الرئيس',
    ap_msg_name:    'آسو باموكي',
    ap_msg_title:   'رئيس مجلس الإدارة، مجموعة حلبجة',
    ap_msg_body1:   'منذ تأسيسنا في حلبجة عام ١٩٩٢، كنا مدفوعين بمهمة واحدة: المساهمة في رخاء وتنمية شعبنا ووطننا.',
    ap_msg_body2:   'رؤيتنا الشاملة هي المساهمة في بناء بلد أفضل يزدهر بالتقدم المستدام والرخاء الدائم — للأجيال الحالية والقادمة.',
    ap_msg_quote:   '"هدفنا أن نكون مزوداً موثوقاً للخدمات والأعمال التي تدعم النمو الاقتصادي والتنمية في البلاد. من خلال توفير التكنولوجيا المتطورة وخلق فرص العمل ودعم المواهب المحلية، نسعى للاستفادة من خبرتنا ومواردنا لتحسين حياة المواطنين."',
    ap_msg_attr:    '— آسو باموكي، رئيس مجلس الإدارة · مجموعة حلبجة',
    ap_timeline_eyebrow: 'مسيرتنا',
    ap_timeline_h1: 'المحطات و',
    ap_timeline_h2: 'الشركات',
    ap_timeline_drag:'١٢ شركة · اسحب للاستكشاف →',
    ap_values_eyebrow: 'أساسنا',
    ap_values_h1:   'ما',
    ap_values_h2:   'نؤمن به',
    ap_values_desc:  'قيمنا ليست كلمات على جدار — إنها المبادئ التي توجه كل قرار وكل مشروع وكل علاقة نبنيها عبر قطاعاتنا الثمانية.',
    ap_val1_n:'٠١', ap_val1_t:'النزاهة',    ap_val1_b:'تعاملات شفافة والتزام راسخ بكل وعد قطعناه لعملائنا وشركائنا.',
    ap_val2_n:'٠٢', ap_val2_t:'التميز',     ap_val2_b:'رفع جودة منتجاتنا وخدماتنا باستمرار لتلبية أعلى المعايير.',
    ap_val3_n:'٠٣', ap_val3_t:'الاستدامة', ap_val3_b:'البناء على المدى البعيد — لعملائنا ومجتمعاتنا وبيئتنا.',
    ap_val4_n:'٠٤', ap_val4_t:'المجتمع',   ap_val4_b:'دعم الكفاءات المحلية وتوفير فرص عمل وفيرة لمواطنينا.',
    ap_cta_h1:  'انضم إلى فريق',
    ap_cta_h2:  'مجموعة حلبجة',
    ap_cta_h3:  '',
    ap_cta_sub: 'نبحث دائماً عن أفراد موهوبين وطموحين للنمو معنا.',
    ap_cta_btn: 'عرض الوظائف المتاحة →',
    cp_eyebrow: 'محفظتنا',
    cp_h1: '٢٣ شركة.',
    cp_h2: '٨ قطاعات.',
    cp_sub: 'من البناء والطاقة إلى التعليم والغذاء، تغطي شركات مجموعة حلبجة كامل اتساع اقتصاد العراق المتنامي.',
    cp_filter_all:         'الكل',
    cp_filter_construction:'البناء',
    cp_filter_energy:      'الطاقة',
    cp_filter_trading:     'التجارة',
    cp_filter_realestate:  'العقارات',
    cp_filter_education:   'التعليم',
    cp_filter_food:        'الغذاء',
    cp_filter_investment:  'الاستثمار',
    cp_filter_services:    'الخدمات',
    cp_learnmore: 'اعرف أكثر',
    np_eyebrow: 'آخر التحديثات',
    np_h1: 'الأخبار و',
    np_h2: 'الإعلانات',
    np_sub: 'ابق على اطلاع بآخر المشاريع والإنجازات والتطورات من مجموعة حلبجة وشركاتها.',
    np_filter_all:           'الكل',
    np_filter_event:         'الفعاليات',
    np_filter_project:       'المشاريع',
    np_filter_corporate:     'الشركات',
    np_filter_people:        'الأشخاص',
    np_filter_infrastructure:'البنية التحتية',
    np_read_full: 'اقرأ القصة كاملة',
    np_read_more: 'اقرأ أكثر',
    np_all_stories: 'جميع القصص',
    crp_eyebrow: 'انضم إلى فريقنا',
    crp_h1: 'ابنِ مسيرتك',
    crp_h2: 'المهنية معنا',
    crp_sub: 'نبحث عن أفراد موهوبين وطموحين لمساعدتنا في النمو عبر ثمانية قطاعات وأربع دول.',
    crp_stat1_n:'٥٠٠+', crp_stat1_l:'موظف',
    crp_stat2_n:'٢٣',   crp_stat2_l:'شركة',
    crp_stat3_n:'٨',    crp_stat3_l:'قطاعات',
    crp_stat4_n:'٤',    crp_stat4_l:'دول',
    crp_filter_all:        'الكل',
    crp_filter_construction:'البناء',
    crp_filter_energy:     'الطاقة',
    crp_filter_trading:    'التجارة',
    crp_filter_education:  'التعليم',
    crp_filter_realestate: 'العقارات',
    crp_filter_admin:      'الإدارة',
    crp_apply_btn: 'قدّم الآن',
    crp_open_h1: 'لم تجد الوظيفة المناسبة؟',
    crp_open_h2: 'أرسل طلباً مفتوحاً',
    crp_open_sub: 'نبحث دائماً عن المواهب. عرّف بنفسك وسنتواصل معك عند توفر الفرصة المناسبة.',
    crp_open_btn: 'أرسل طلباً مفتوحاً →',
    modal_title:   'تقديم طلب لهذا المنصب',
    modal_close:   '×',
    modal_sec1:    'المعلومات الشخصية',
    modal_name:    'الاسم الكامل',
    modal_email:   'البريد الإلكتروني',
    modal_phone:   'رقم الهاتف',
    modal_nationality: 'الجنسية',
    modal_sec2:    'الخلفية المهنية',
    modal_exp:     'سنوات الخبرة',
    modal_jobtitle:'المسمى الوظيفي الحالي',
    modal_linkedin:'ملف LinkedIn (اختياري)',
    modal_skills:  'المهارات الرئيسية',
    modal_skills_ph:'اكتب مهارة واضغط Enter…',
    modal_cover:   'خطاب التقديم',
    modal_cover_ph:'أخبرنا لماذا أنت المناسب…',
    modal_cv:      'رفع السيرة الذاتية',
    modal_cv_sub:  'اسحب وأفلت أو انقر للرفع — PDF, DOC, DOCX',
    modal_submit:  'إرسال الطلب',
    modal_success_h: 'تم استلام طلبك!',
    modal_success_b: 'شكراً لتقديمك. سيراجع فريقنا طلبك ويتواصل معك خلال ٥-٧ أيام عمل.',
    modal_back:    '← العودة إلى الوظائف',
    back_main: '← العودة للصفحة الرئيسية',
    copyright:  '© ٢٠٢٦ مجموعة حلبجة. جميع الحقوق محفوظة.',
  }
};

/* ── ENGINE ──────────────────────────────────────────────── */
let currentLang = localStorage.getItem('hg_lang') || 'en';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('hg_lang', lang);
  applyLang();
}

function applyLang() {
  const t = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
  const rtl = currentLang !== 'en';
  const html = document.documentElement;

  // Direction
  html.setAttribute('dir', rtl ? 'rtl' : 'ltr');
  html.setAttribute('lang', currentLang === 'ku' ? 'ckb' : currentLang === 'ar' ? 'ar' : 'en');

  // Font
  html.style.fontFamily = rtl
    ? "'Noto Sans Arabic', 'Segoe UI', Arial, sans-serif"
    : "'Helvetica Neue', Arial, sans-serif";

  // Text nodes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.textContent = t[key];
  });

  // HTML nodes (bold, spans etc.)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.dataset.i18nHtml;
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  // Placeholders
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.dataset.i18nPh;
    if (t[key] !== undefined) el.placeholder = t[key];
  });

  // Active lang button
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === currentLang);
  });
}

// Run on load
document.addEventListener('DOMContentLoaded', applyLang);
